### ISSUE TITLE
locales folder

### ISSUE THREAD

**Issue by ovari** [ether/ep_desktop_notifications#10]
Please add a `locales` folder to enable translations into other languages.

For example, `Desktop notifications` in `<label for="options-desktopNotifications">Desktop notifications</label>`
https://github.com/JohnMcLear/ep_desktop_notifications/blob/master/templates/desktop_notifications_entry.ejs#L3

Thank you

**Comment by JohnMcLear** [comment]
done

**Comment by ovari** [comment]
Could you please advise where the `locales` folder is?

We couldn't see it at https://github.com/ether/ep_desktop_notifications/
![image](https://user-images.githubusercontent.com/17465872/106946760-a2830300-677d-11eb-9585-d788ff205e2f.png)

Thank you

**Comment by ovari** [comment]
The line `<label for="options-desktopNotifications">Desktop notifications</label>` at https://github.com/ether/ep_desktop_notifications/blob/master/templates/desktop_notifications_entry.ejs#L3 doesn't seem to have changed.
![image](https://user-images.githubusercontent.com/17465872/106946935-e118bd80-677d-11eb-94e3-4ea086aa1551.png)

Thank you

**Comment by JohnMcLear** [comment]
Wow thanks for spotting this..  Thankfully I kept the plugin on my file system...  The push failed w/ the locales logic in!

**Comment by ovari** [comment]
Are you able to reopen this issue and close it with a reference to the push issue which resolves it? Thank you

**Comment by ovari** [comment]
Please ignore above message as we see the `locales` folder. Thank you once again
