### ISSUE TITLE
Problems on Android 7.0

### ISSUE THREAD

**Issue by fosils** [ether/ep_desktop_notifications#5]
I really see a potential in this plugin. Especially in combination with the auto-completion plugin, so I could mention specific people by writing @theirusername directly in the document and have them notified.

Anyways, I encountered an error. I tried to have a chat with myself. One client was a desktop chrome browser where the notifications worked perfectly. The other client was Chrome on my Android 7.0. When I wrote a message from the desktop to the android I got the following error:
https://www.screencast.com/t/gpOuMcLSw

The other way around worked fine.

**Comment by JohnMcLear** [comment]
Should be fine now but if you have a problem still let me know :)
